version: '3.1'
services: 
    mongodb:
        image: 'mongo:latest'
        restart: always
        ports: 
          - 27017:27017
        volumes:
          - mongod_data:/data/db
volumes: 
  mongod_data: