version: '3.1'
services: 
    mongodb:
        image: 'bitnami/mongodb:latest'
        restart: always
        ports: 
          - 27017:27017
        volumes:
          - D://container_tools/mongodb:/bitnami/mongodb