version: '3'
services:
    elasticsearch1:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.8.4
        environment:
          - node.name=elasticsearch
          - discovery_type=single-node
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
          memlock:
            soft: -1
            hard: -1
        ports:
          - "9200:9200"