version: '2'

services: 
    redis:
        image: 'bitnami/redis:latest'
        restart: always
        environment: 
          - ALLOW_EMPTY_PASSWORD=yes
        networks: 
          - app-tier
    redis-sentinel:
        image: 'bitnami/redis-sentinel:latest'
        environment: 
          - REDIS_MASTER_HOST=redis
        ports: 
          - 26379:26379
        networks: 
          - app-tier
networks: 
  app-tier:
    driver: bridge